# Generated by Django 3.1.14 on 2023-03-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Telephone',
        ),
    ]
